version: "3.9"
services:
    api:
        container_name: api
        image: docker.io/library/lelo
        build:
            context: ./src
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - database
        environment:
            ConnectionStrings__DefaultConnection: "Host=database;Database=postgres;Username=postgres;Password=postgres"
    database:
        container_name: database
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"

volumes:
    pgdata: {}




